version: "3.7"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=hospitalvisao
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
